// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicodeBlazor.Server.Model;

namespace UnicodeBlazor.Server.Migrations
{
    [DbContext(typeof(UnicodeBlazorContext))]
    partial class UnicodeBlazorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnicodeBlazor.Shared.UnicodeBlockEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("End")
                        .HasColumnType("int");

                    b.Property<int>("Start")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("UnicodeBlazor.Shared.UnicodeCharacterEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Codepos")
                        .HasColumnType("int");

                    b.Property<string>("BlockId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CssCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnicodeVersion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name", "Codepos");

                    b.HasIndex("BlockId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("UnicodeBlazor.Shared.UnicodeCharacterEntry", b =>
                {
                    b.HasOne("UnicodeBlazor.Shared.UnicodeBlockEntry", "Block")
                        .WithMany("Characters")
                        .HasForeignKey("BlockId");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("UnicodeBlazor.Shared.UnicodeBlockEntry", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
